name: Daily Jobs

on:
  schedule:
      - cron: "45 0 * * *"

jobs:
  atlas:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    name: Refresh RIPE Atlas probe list
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get latest data
        run: rm -rf starlink-geoip-data && git clone https://github.com/clarkzjw/starlink-geoip-data.git && rm -rf starlink-geoip-data/.git
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install dnsutils -y && poetry install
      - name: Refresh Atlas probe list
        run: poetry run python3 scripts/atlas.py
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:clarkzjw/starlink-geoip-data.git
          BRANCH: master
          FOLDER: starlink-geoip-data
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          MESSAGE: "GitHub Action Update - RIPE Atlas Probe List for Starlink"
          SKIP_EMPTY_COMMITS: true
          CLEAR_GLOBS_FILE: ".clear-target-files"

  peeringdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    name: Refresh PeeringDB Info
    needs: [atlas]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get latest data
        run: rm -rf starlink-geoip-data && git clone https://github.com/clarkzjw/starlink-geoip-data.git && rm -rf starlink-geoip-data/.git
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Refresh PeeringDB Info
        run: poetry run python3 scripts/peeringdb.py
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:clarkzjw/starlink-geoip-data.git
          BRANCH: master
          FOLDER: starlink-geoip-data
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          MESSAGE: "GitHub Action Update - PeeringDB Info for Starlink"
          SKIP_EMPTY_COMMITS: true
          CLEAR_GLOBS_FILE: ".clear-target-files"
