name: Monthly latency json refresh

on:
  schedule:
      - cron: "0 0 2 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    name: Refresh monthly latency json
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get latest data
        run: rm -rf starlink-geoip-data && git clone https://github.com/clarkzjw/starlink-geoip-data.git && rm -rf starlink-geoip-data/.git

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Refresh GeoIP
        run: poetry run python3 scripts/get_monthly_latency_snapshot.py

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:clarkzjw/starlink-geoip-data.git
          BRANCH: master
          FOLDER: starlink-geoip-data
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          MESSAGE: "GitHub Action Update - Monthly Starlink Latency Snapshot"
          SKIP_EMPTY_COMMITS: true
          CLEAR_GLOBS_FILE: ".clear-target-files"