name: Hourly Jobs

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"


jobs:
  geoip:
    runs-on: [self-hosted, starlink]
    permissions:
      contents: write
      packages: write
      id-token: write
    name: Refresh GeoIP
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Get latest data
        run: rm -rf starlink-geoip-data && git clone --depth=1 https://github.com/clarkzjw/starlink-geoip-data.git && rm -rf starlink-geoip-data/.git
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install pipx dnsutils -y
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install poetry
        run: pipx install poetry && pipx ensurepath
      - name: Install project dependencies
        run: poetry install
      - name: Refresh GeoIP
        run: env PYTHONUNBUFFERED=1 poetry run python3 geoip_pop.py
      - name: Push GeoIP
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:clarkzjw/starlink-geoip-data.git
          BRANCH: master
          FOLDER: starlink-geoip-data
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          MESSAGE: "GitHub Action Update - Starlink GeoIP Feed"
          SKIP_EMPTY_COMMITS: true
          CLEAR_GLOBS_FILE: ".clear-target-files"


